language: node_js
node_js:
  - 0.10
  - 0.8
services:
  - redis-server
addons:
  postgresql: 9.3
before_script:
  - psql -c 'create database "tomatar-test";' -U postgres
  - psql -f ./config/tables.sql -U postgres -d tomatar-test
  - npm install --quiet -g karma
  - npm install --quiet -g grunt-cli
  - npm install --quiet -g bower
  - bower install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
  - NODE_ENV=test grunt cafemocha
