language: node_js
node_js:
  - 0.10
  - 0.8

before_script:
  - npm install --quiet -g karma
  - npm install -g grunt-cli
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 1
script:
  - karma start config/karma.conf.js --no-auto-watch --single-run --reporters=dots --browsers=Firefox
